# 04_workloads/manifests/ai-engine/triton-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  namespace: default
  labels:
    app: triton-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-inference
  template:
    metadata:
      labels:
        app: triton-inference
    spec:
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:23.10-py3
        # O comando de start que carrega os modelos
        command: ["tritonserver", "--model-repository=/models", "--log-verbose=1"]

        resources:
          limits:
            nvidia.com/gpu: 1  # A mágica que pega a GPU física
          requests:
            memory: "4Gi"
            cpu: "2"

        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics

        volumeMounts:
        - mountPath: /models
          name: model-repo
          readOnly: true

      volumes:
      - name: model-repo
        hostPath:
          # ATENÇÃO: Essa pasta deve existir no seu servidor físico (Ubuntu)
          path: /opt/ai-models
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: triton-service
spec:
  selector:
    app: triton-inference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: grpc
  type: ClusterIP