apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-inference-server
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:23.10-py3
        command: ["/bin/sh", "-c"]
        # Flags essenciais:
        # --model-control-mode=poll: Permite adicionar modelos "a quente" sem reiniciar
        # --repository-poll-secs=5: Checa a pasta a cada 5 segundos
        args: ["tritonserver --model-repository=/models --allow-gpu-metrics=true --log-verbose=1 --model-control-mode=poll --repository-poll-secs=5"]
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        volumeMounts:
        - mountPath: /models
          name: model-repo
      volumes:
      - name: model-repo
        hostPath:
          path: /home/gabrielsousa/triton_models
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: triton-service
spec:
  selector:
    app: triton
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: grpc
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: metrics